apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v1
    appVersion: 11.8.0
    created: "2021-06-07T10:19:25.023385166+05:30"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 0.x.x
    description: Chart for PostgreSQL, an object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: ff2a79314bc60c6cd94bfb4b792fb523cee9fbbe5ef1956aa7c6b9135159ca1e
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-9.1.1.tgz
    version: 9.1.1
  openproject:
    apiVersion: v1
    created: "2021-06-07T10:19:25.023385166+05:30"
generated: "2022-14-01T10:19:24.991901979+05:30"
