apiVersion: v2
kubeVersion: ">= 1.12"
appVersion: 1.16.0
description: "Keyoxide allows you to prove 'ownership' of accounts on websites, domain names, IM, etc., regardless of your username. Keyoxideâ€™s purpose is just that: linking online properties together. Keyoxide uses an 'open source, decentralized and cryptography-based approach to bidirectional linking'."
name: keyoxide-web
home: https://keyoxide.org/
type: application
version: 0.2.0
sources:
  - https://codeberg.org/keyoxide/keyoxide-web
maintainers:
  - name: ajayvarma-ittrident
    email: ajayvarma@tridentsqa.com
  - name: srinivasanbr
    email: brsrinivasan98@gmail.com
icon: https://codeberg.org/keyoxide/keyoxide-web/raw/branch/main/static/img/logo_circle.png
annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/itTrident/helm-charts/tree/main/charts/keyoxide-web
    - name: Keyoxide
      url: https://keyoxide.org
